version: '3.7'
services:
  mysql:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
    ports:
      - '3306:3306'
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - app

  adminer:
    image: adminer:4.7.6
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
    networks:
      - app

  api:
    build:
      context: api
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    networks:
      - app

  dashboard:
    build:
      context: frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - '80:3000'
    volumes:
      - .:/app

volumes:
  db_volume:

networks:
  app:
