version: '3.7'

services:
  mysql:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
    ports:
      - '3306:3306'
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - app

  adminer:
    image: adminer:4.7.6
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    networks:
      - app

  api:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    env_file:
      - backend/development.env
    environment:
      - NODE_ENV=development
      - IGNORE_ENV_FILE=false
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    networks:
      - app

  dashboard:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    env_file:
      - frontend/.env
    environment:
      - NODE_ENV=development
    ports:
      - '80:3001'
    volumes:
      - ./frontend:/app
    stdin_open: true

volumes:
  db_volume:

networks:
  app:
