FROM node:14.15.1-alpine as builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --silent

COPY . .
RUN npm run build

RUN rm -r node_modules
RUN npm ci install --production --silent


FROM node:14.15.1-alpine

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY --from=builder /app /app

WORKDIR /app

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
