FROM node:14.15.1-alpine as builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
COPY . .


FROM node:14.15.1-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

COPY --from=builder /app /app

WORKDIR /app
EXPOSE 3000

CMD ["npm", "run", "start:dev"]
