FROM node:12.16.3-alpine as builder

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY package*.json ./
RUN npm ci --silent

COPY . .
RUN npm run build


FROM node:12.16.3-alpine

COPY --from=builder /app /app

WORKDIR /app

EXPOSE 3000

CMD ["npm", "run", "start:prod"]