# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Backend testing job
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm lint
      - name: Run all tests
        run: npm test

  test-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Frontend testing job
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm lint
      - name: Run all tests
        run: npm test
